version: "3"

services:
  bc1:
    container_name: interface-server1
    image: bcinterface:0.1
    ports:
      - 50051:50051
    command: ["-verifynode=verify-server1:50053"]
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - test-verifier_bc_interface

  mongo1:
    container_name: mongo1
    image: mongo:4.4.6
    #user: "0:0"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=peer_information
    volumes:
      - ./rs_keyfile:/etc/mongodb/pki/keyfile
      - ~/data/mongo1:/data/db
      #- ~/data/mongo:/data/db
      #- mongo1_data:/data/db
    networks:
      - test-verifier_bc_interface

  mongo2:
    container_name: mongo2
    image: mongo:4.4.6
    #user: "0:0"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=peer_information
    volumes:
      - ./rs_keyfile:/etc/mongodb/pki/keyfile
      - ~/data/mongo2:/data/db
      #- ~/data/mongo:/data/db
      #- mongo2_data:/data/db
    networks:
      - test-verifier_bc_interface

  mongo3:
    container_name: mongo3
    image: mongo:4.4.6
    #user: "0:0"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=peer_information
    volumes:
      - ./rs_keyfile:/etc/mongodb/pki/keyfile
      - ~/data/mongo3:/data/db
      #- ~/data/mongo:/data/db
      #- mongo3_data:/data/db
    networks:
      - test-verifier_bc_interface

networks:
  test-verifier_bc_interface:
    external: true